{"name": "Проверка создания заказа с неверным хешем ингредиентов", "status": "passed", "description": "Создаём пользователя, авторизуемся им и создаём заказ с рандомно сгенерированным хэшем ингредиентов. Проверяем, что вернулась 500 ошибка. После проверки удаляем пользователя", "steps": [{"name": "Авторизуем юзера", "status": "passed", "start": 1718372711358, "stop": 1718372711655}, {"name": "Создаём заказ", "status": "passed", "start": 1718372711655, "stop": 1718372711875}], "start": 1718372711358, "stop": 1718372711875, "uuid": "f2ef57e9-19f2-4e7e-b233-baa5d5f67e15", "historyId": "2c2489a338fb3f0c837ba0314bbc0e4c", "testCaseId": "2c2489a338fb3f0c837ba0314bbc0e4c", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_hash_ingredients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "Kotiki"}, {"name": "thread", "value": "21656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}