{"name": "Проверяем изменение емейла без авторизации", "status": "passed", "description": "Создаём пользователя и меняем емейл, отправляя пустой accessToken. Проверяем, что вернулась ошибка. Текст ошибки: \"You should be authorised\". После проверки удаляем юзера", "steps": [{"name": "Создаём юзера", "status": "passed", "start": 1717572716247, "stop": 1717572716544}, {"name": "Изменяем данные юзера", "status": "passed", "start": 1717572716544, "stop": 1717572716737}, {"name": "Удаляем юзера", "status": "passed", "start": 1717572716737, "stop": 1717572717177}], "start": 1717572716247, "stop": 1717572717177, "uuid": "249ea93c-4ca5-4783-b458-49a431d7f980", "historyId": "6470b18b72aa1b6361087e8be7c03ad6", "testCaseId": "6470b18b72aa1b6361087e8be7c03ad6", "fullName": "tests.test_changing_user_data.TestChangingUserData#test_change_email_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_changing_user_data"}, {"name": "subSuite", "value": "TestChangingUserData"}, {"name": "host", "value": "Kotiki"}, {"name": "thread", "value": "15004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_changing_user_data"}]}